### ISSUE TITLE
Spiel zuckt noch, obwohl gestorben

### ISSUE THREAD

**Issue by kinnla** [NummerEins/dive#113]
PRECONDITION: Der Taucher ist in einen Hai geschwommen und gestorben, zwei Buttons "Menu" und "Restart" sind sichtbar.
ACTION: Wechsle über Alt + Tab in eine andere Applikation (z.B. Browser), und dann wieder zurück zum Spiel.
OBSERVED BEHAVIOR: Das Fress-Geräusch wird abgespielt und der Taucher bewegt sich einen Frame weiter
EXPECTED BEHAVIOR: Nichts passiert, kein Geräusch, Taucher bewegt sich nicht weiter.

Man kann das so weit treiben, dass der Taucher durch den Hai durchschwimmt, und man das Spiel normal weiterspielen kann.

**Comment by Naronios** [comment]
Ist erledigt
