### ISSUE TITLE
Zu wenig Müllgenerierung

### ISSUE THREAD

**Issue by rehaia** [NummerEins/dive#87]
PRECONDITION: Das Spiel läuft
ACTION: Spiele so lange wie möglich
ACTUAL BEHAVIOR: Nach einiger Zeit wird in der Desktop Version sehr wenig Müll generiert
EXPECTED BEHAVIOR: Mehr Müll wird erzeugt, der eingesammelt werden kann
![lesstrash](https://cloud.githubusercontent.com/assets/7746175/13929329/eff2e90e-ef99-11e5-9a5b-8f69fa1bdbef.png)

**Comment by lisaSWP** [comment]
Habe mich drum gekümmert und die Abstände heruntergesetzt. Ich hoffe es ist jetzt besser. Wenn du glaubst dass es immer noch zu wenig ist, sag Bescheid.
