### ISSUE TITLE
Kollision obwohl keine Kollision

### ISSUE THREAD

**Issue by kinnla** [NummerEins/dive#88]
PRECONDITION: Taucher taucht unter einem Schiff
ACTION: Auftauchen, ohne das Schiff zu berühren
OBSERVED BEHAVIOUR: Game Over aufgrund einer Kollision
EXPECTED BEHAVIOUR: Spiel läuft weiter
![image](https://cloud.githubusercontent.com/assets/3518808/13933803/45798b52-efaf-11e5-968c-3a75216edba0.png)

**Comment by Naronios** [comment]
ship.png zugeschnitten und Kollisionsfläche des Tauchers verkleinert
