### ISSUE TITLE
gh-pages branch in remote repository

### ISSUE THREAD

**Issue by amoSWP** [NummerEins/dive#89]
PRECONDITION: Die website ist auf extra repository amoswp.github.io
ACTION: Rufe website über eigenes repository  https://github.com/NummerEins/dive auf
ACTUAL BEHAVIOR: remote branch gh-pages lässt sich nicht erstellen
EXPECTED BEHAVIOR: branch gh-pages wird erstellt und darüber wird die website aufgerufen

**Comment by Naronios** [comment]
Funktioniert jetzt
