### ISSUE TITLE
Website auf anderen Rechnern anpassen

### ISSUE THREAD

**Issue by Naronios** [NummerEins/dive#94]
PRECONDITION: arbeiten auf Laptop
ACTION: Aufrufen der Website auf Laptop
OBSERVED BEHAVIOUR: Spiel wird unten rechts erstellt und es muss nach unten rechts gescrollt werden
EXPECTED BEHAVIOUR: Spiel ist unten aber zentriert

**Comment by lisaSWP** [comment]
Done!
